[REVERSI_PACKAGES]
  EMPTY=0
  WHITE=1
  BRACK=-1
  DRAW=2
  ERROR=-999
  SQUARE_NUM=64
  CHANGE_COLOR=-1
  UP=[0,1]
  UPPER_RIGHT=[1,1]
  RIGHT=[1,0]
  LOWER_RIGHT=[1,-1]
  LOW=[0,-1]
  LOWER_LEFT=[-1,-1]
  LEFT=[-1,0]
  UPPER_LEFT=[-1,1]

[MARKS]
  EMPTY=" "
  WHITE="⚪️"
  BLACK="⚫️"
